;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
      autopair-insert-opening
      autopair-newline
      clean-aindent--bsunindent
      electric-newline-and-maybe-indent
      eval-last-sexp
      evil-a-word
      evil-backward-char
      evil-backward-word-begin
      evil-change
      evil-delete
      evil-digit-argument-or-evil-beginning-of-line
      evil-end-of-line
      evil-find-char
      evil-forward-char
      evil-forward-word-begin
      evil-jump-item
      evil-next-line
      evil-next-line-1-first-non-blank
      evil-normal-state
      evil-previous-line
      evil-window-down
      evilnc-comment-or-uncomment-lines
      forward-sentence
      forward-sexp
      helm-M-x
      highlight-symbol-mode
      indent-for-tab-command
      kill-region
      mouse-set-region
      tab-indent-or-complete
      web-mode-comment-indent-new-line
      whole-line-or-region-kill-region
      ))

(setq mc/cmds-to-run-once
      '(
      avy-goto-word-1-below
      delete-window
      describe-key
      dired-unmark-backward
      emmet-expand-line
      evil-emacs-state
      helm-projectile-ag
      keyboard-quit
      mark-whole-buffer
      mc/mark-next-lines
      mc/mark-previous-lines
      ))
