;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
      autopair-insert-opening
      autopair-newline
      clean-aindent--bsunindent
      eval-last-sexp
      evil-a-word
      evil-change
      evil-window-down
      evilnc-comment-or-uncomment-lines
      forward-sentence
      helm-M-x
      highlight-symbol-mode
      mouse-set-region
      web-mode-comment-indent-new-line
      ))

(setq mc/cmds-to-run-once
      '(
      avy-goto-word-1-below
      describe-key
      dired-unmark-backward
      emmet-expand-line
      evil-avy-goto-char-2
      evil-backward-word-begin
      evil-digit-argument-or-evil-beginning-of-line
      evil-downcase
      evil-emacs-state
      evil-ex-search-next
      evil-find-char-to
      evil-forward-word-begin
      evil-goto-line
      evil-inner-word
      evil-mouse-drag-region
      evil-next-line
      evil-normal-state
      evil-previous-line
      evil-previous-line-first-non-blank
      evil-substitute
      evil-visual-char
      highlight-symbol-next
      keyboard-quit
      mc/mark-next-lines
      mc/mark-previous-lines
      web-mode-tag-next
      ))
