;;; redshank-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from redshank.el

(autoload 'redshank-mode "redshank" "\
Minor mode for editing and refactoring (Common) Lisp code.

\\{redshank-mode-map}

This is a minor mode.  If called interactively, toggle the
`Redshank mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `redshank-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'turn-on-redshank-mode "redshank" "\
Turn on Redshank mode.  Please see function `redshank-mode'.

This function is designed to be added to hooks, for example:
  (add-hook 'lisp-mode-hook 'turn-on-redshank-mode)" t)
(autoload 'asdf-mode "redshank" "\
Major mode for ASDF files.  This mode is derived from `lisp-mode'
and activates minor mode `redshank-mode' by default.

\\{asdf-mode-map}

(fn)" t)
(autoload 'turn-on-asdf-mode "redshank" "\
Turn on ASDF mode.  Please see function `asdf-mode'.

This function is designed to be added to hooks, for example:
  (add-hook 'lisp-mode-hook 'turn-on-asdf-mode)" t)
(register-definition-prefixes "redshank" '("redshank-"))


;;; Generated autoloads from redshank-loader.el

(autoload 'redshank-setup "redshank-loader" "\
Installs `redshank-mode' on major mode hooks listed in HOOKS.
If AUTOINSERTP is non-nil and `auto-insert-mode' is available,
activate support for that, too.

(fn HOOKS &optional AUTOINSERTP)")

;;; End of scraped data

(provide 'redshank-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; redshank-autoloads.el ends here
