;;; html-to-hiccup-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from html-to-hiccup.el

(autoload 'html-to-hiccup-convert-region "html-to-hiccup" "\
Convert the region between START and END from HTML to Hiccup.
If BODYTAGS is non-nil, skip the first element returned from the HTML parser.

(fn START END &optional BODYTAGS)" t)
(autoload 'html-to-hiccup-yank "html-to-hiccup" "\
Like `yank' but insert killed HTML as Hiccup.
ARGs are the same as in the `yank' command.

Code is copied from the `yank' function in simple.el.

(fn &optional ARG)" t)
(register-definition-prefixes "html-to-hiccup" '("html-to-hiccup-"))

;;; End of scraped data

(provide 'html-to-hiccup-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; html-to-hiccup-autoloads.el ends here
