;; Custom rules for php files
;; By default all php files are in web mode (mix of html / php / js / css)
(add-to-list 'auto-mode-alist '(".*.php" . web-mode))
(add-to-list 'auto-mode-alist '("model/.*/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("lib/.*/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("process/.*/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("service/.*/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("lang/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("conf/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("ajax/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("controller/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("cron/.*.php" . php-mode))
(add-to-list 'auto-mode-alist '("_lang_de.inc.php" . php-mode))
(add-to-list 'auto-mode-alist '("_lang_fr.inc.php" . php-mode))
(add-to-list 'auto-mode-alist '("_lang_en.inc.php" . php-mode))

(add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
;; (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.css\\'" . css-mode))
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-mode))
(add-to-list 'auto-mode-alist '("\\.jade\\'" . jade-mode))
(add-to-list 'auto-mode-alist '("\\.as\\'" . actionscript-mode))
(add-to-list 'auto-mode-alist '("\\.htaccess\\'" . conf-mode))
(add-to-list 'auto-mode-alist '("\\.jar$" . archive-mode)) ; Open jar files in archive mode