(require 'yasnippet)
(require 'company)
(require 'company-web-html)
(require 'company-web)

(setq company-show-numbers t)
(setq company-minimum-prefix-length 3)
(setq company-dabbrev-downcase nil)
(setq company-dabbrev-downcase 0) 
(setq company-dabbrev-downcase nil)
(setq company-idle-delay 0.2)
(setq company-tooltip-align-annotations t)
(setq company-tooltip-limit 16)
(setq company-require-match nil)
(setq company-quickhelp-mode 1)
(setq company-quickhelp-delay 1)
(setq company-quickhelp-max-lines nil)
(setq yas-indent-line 'auto)

(add-hook 'after-init-hook 'global-company-mode)
(company-quickhelp-mode 1)

;; Remove some words completion
(delete 'company-dabbrev company-backends)
(delete '(company-dabbrev-code company-gtags company-etags company-keywords) company-backends)
