;;; actionscript-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from actionscript-mode.el

(autoload 'actionscript-mode "actionscript-mode" "\
Major mode for editing Actionscript files.
\\{actionscript-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.as\\'" . actionscript-mode))
(register-definition-prefixes "actionscript-mode" '("actionscript-" "preprocessor-kwds" "reload-actionscript-mode"))

;;; End of scraped data

(provide 'actionscript-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; actionscript-mode-autoloads.el ends here
